# Generated by Django 2.0.1 on 2018-01-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=200)),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('death_year', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_for', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('title_type', models.CharField(max_length=50)),
                ('primary_title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('is_adult', models.BooleanField()),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(null=True)),
                ('runtime_minutes', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Genre')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Title')),
            ],
        ),
        migrations.AddField(
            model_name='principal',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Title'),
        ),
        migrations.AddField(
            model_name='nameprofession',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Profession'),
        ),
    ]
