# Generated by Django 2.0.1 on 2018-01-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
