# Generated by Django 2.0.1 on 2018-01-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20180103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='original_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='primary_title',
            field=models.TextField(),
        ),
    ]
