# Generated by Django 2.0.1 on 2018-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20180103_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.TextField(null=True),
        ),
    ]
