# Generated by Django 2.0.1 on 2018-01-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20180104_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='birth_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_title',
            field=models.TextField(null=True),
        ),
    ]
