# Generated by Django 2.0.1 on 2018-01-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20180104_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='primary_title',
            field=models.TextField(null=True),
        ),
    ]
