# Generated by Django 2.0.1 on 2018-01-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_auto_20180105_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='known_for',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='end_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_adult',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
