# Generated by Django 2.0.1 on 2018-01-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_auto_20180105_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='known_for',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_adult',
            field=models.IntegerField(),
        ),
    ]
