# Generated by Django 2.0.1 on 2018-01-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_auto_20180105_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
