# Generated by Django 2.0.1 on 2018-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0013_auto_20180105_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='known_for',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_adult',
            field=models.BooleanField(),
        ),
    ]
