# Generated by Django 2.0.1 on 2018-01-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0014_auto_20180107_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameprofession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nameprofession',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='titlegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titlegenre',
            name='title',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='known_for',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='NameProfession',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
