# Generated by Django 2.0.1 on 2018-01-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0015_auto_20180108_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='known_for',
            field=models.TextField(null=True),
        ),
    ]
