# Generated by Django 2.0.1 on 2018-01-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0018_principal_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='e',
        ),
    ]
