# Generated by Django 2.0.1 on 2018-01-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0020_auto_20180110_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titles', models.TextField()),
                ('costar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costar', to='scores.Name')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='scores.Name')),
            ],
        ),
    ]
