# Generated by Django 2.0.1 on 2018-01-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0021_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='in_graph',
            field=models.BooleanField(default=False),
        ),
    ]
